### ISSUE TITLE
Feature Request: font style setting (italic, bold, underline)

### ISSUE THREAD

**Issue by dominicpalmer** [0verEngineer/InlineProblems#20]
It would be great to allow users to specify font styling in the box/label settings section:

![image](https://user-images.githubusercontent.com/32597988/229321517-ec5183cf-636b-41b2-adc1-f217e92dc2db.png)

**Comment by 0verEngineer** [comment]
Thanks for the request, i will implement that when i have some time and after all bugs / problems in my list and in the issue tracker are resolved. In the meantime i am open for pull requests.

**Comment by 0verEngineer** [comment]
I have implemented font settings, however underscore was not available and i think if it is really needed then we need special handling for that.
Bold and italic are implemented and will be available in Releas 0.4.0.
https://github.com/0verEngineer/InlineProblems/pull/25

**Comment by dominicpalmer** [comment]
Amazing, thanks! I primarily needed italic, so no issue at all if underline is missing.
