### ISSUE TITLE
Feature Request: setting to left-prioritise errors

### ISSUE THREAD

**Issue by dominicpalmer** [0verEngineer/InlineProblems#21]
### Issue

When a line contains more than one problem, the resulting labels aren't ordered by problem severity. And moreover, the labels aren't always ordered by where on the line the problem originates, either.

For example, I'd expect these two lines to have the errors (red) displayed furthest left. Only the first line has this, despite the problems being ordered the same:

![image](https://user-images.githubusercontent.com/32597988/229322479-a40e0398-2ca4-46c3-95eb-2276e9d02aad.png)

### Suggestions

Possible approaches for when a line contains multiple problems of different severities:

i) Display all problems, but first order by problem severity and then by problem location on the line. This gives the user a list of 'things' to work through, prioritised by importance.
ii) Only ever display problems of the highest severity for a given line. Only once the highest severity problems are resolved do the next highest severity problems get displayed. FYI this is how similar plugins for other editors work. Here's Visual Studio:

![inlineproblems](https://user-images.githubusercontent.com/32597988/229322916-d4329fe7-0de7-4322-8cb9-7aee1bd50f6c.gif)

**Comment by 0verEngineer** [comment]
Hey, thanks for the detailed bug report, i have this problem already in my list as well.

The reason why this is not implemented yet is that we have multiple ways to get the problems and not all of them behave the same.

To order them we will need some special handling when adding problems, i hope this will be performant with all problem collectors.

It is easy to implement for the `HighlightProblemListener` and for the ManualScanner as they update from a complete list of new problems on each change.
The `MarkupModelProblemListener` instead works with change events and updates one problem for each event, so thats not that easy to do.

I would like to implement both of your suggestions, with a toggle to switch between them.

I try to do this for the next release as it bothers me as well.

**Comment by 0verEngineer** [comment]
https://github.com/0verEngineer/InlineProblems/pull/22

**Comment by 0verEngineer** [comment]
I closed the other PR because my implementation was bad.

https://github.com/0verEngineer/InlineProblems/pull/23

**Comment by dominicpalmer** [comment]
Awesome. Thank you for this change 👍
