### ISSUE TITLE
Problems with GENERIC_SERVER_ERROR_OR_WARNING severity shown as infos

### ISSUE THREAD

**Issue by zenwarr** [0verEngineer/InlineProblems#28]
At least some external linters use GENERIC_SERVER_ERROR_OR_WARNING severity for their errors (I use golangci-lint with Go Linter plugin, and it does exactly this). In its current state, this plugin only shows such problems as infos, but I prefer to not enable infos as it makes the editor very noisy.

I think it would be best to add another category to allow users to enable showing problems of this type (I have built a custom version of this plugin to treat such problems as warnings (https://github.com/zenwarr/InlineProblems), but I don't think this is the right approach).

**Comment by 0verEngineer** [comment]
Thanks a lot for reporting i will look into it :)

**Comment by 0verEngineer** [comment]
Done in https://github.com/0verEngineer/InlineProblems/pull/33

Now you can add the severity values as semicolon separated integer list to the problem levels in the settings, add 100 to Warning should do the trick for you.
You can also setup the beta channel and check it out as soon as the beta is released.

**Comment by zenwarr** [comment]
Thank you, works perfectly!
