### ISSUE TITLE
the problem label has bug

### ISSUE THREAD

**Issue by gzxy-0102** [0verEngineer/InlineProblems#3]
![image](https://user-images.githubusercontent.com/8954610/210690413-37e01385-2af3-49b9-bf16-5916f8d11abe.png)

**Comment by 0verEngineer** [comment]
Hey @gzxy-0102  
These square boxes are drawn if the font the IDE uses (Settings -> Editor -> Font) does not have the required symbol, can you please change to a font that has the symbols for your language and test it out? It's hard for me to test.

Thanks a lot

**Comment by Sakura-Luna** [comment]
@0verEngineer The plug-in design is unreasonable. The IDE provides a rollback font setting to display characters that are not supported by the main font, while the plug-in only displays squares.

**Comment by 0verEngineer** [comment]
@Sakura-Luna Thanks a lot for the tip with the rollback font setting, i did not know about it. However i do not think that this does make my plug-in design unreasonable. :smile: 

@gzxy-0102 

I have just published the version 0.2.0 which includes the fallback font loading. After the Update you will be able to use the fallback font for characters not found in the normal font.

**Comment by gzxy-0102** [comment]
> 

ok, thank you very much
