### ISSUE TITLE
A short description for problem listener option

### ISSUE THREAD

**Issue by zenwarr** [0verEngineer/InlineProblems#34]
I think it would be beneficial to add a little explanation for "enabled problem listener" option in settings dialog. They behave a little different and seem to have varying performance penalties for the editor, but it is difficult to understand the exact differences between them without looking at source code. Maybe add a little description to the select?

**Comment by 0verEngineer** [comment]
Done in https://github.com/0verEngineer/InlineProblems/commit/d8f5ebd9bf25e7c0d7fa5b25fdcdc5b917377c2e
