### ISSUE TITLE
Localization Issues (Beta)

### ISSUE THREAD

**Issue by 0verEngineer** [0verEngineer/InlineProblems#43]
1. If Windows or Gnome is set to German it uses the german bundle, but it does not work in KDE.
2. The german umlauts are not displaying.

**Comment by 0verEngineer** [comment]
@kuweiguge On what OS did you build and test the localization stuff?

**Comment by kuweiguge** [comment]
> @kuweiguge On what OS did you build and test the localization stuff?

MacOS 13.0.1 (22A400)
IntelliJ IDEA 2023.2.1

**Comment by 0verEngineer** [comment]
@kuweiguge Thanks a lot, i think i will just ignore it on KDE as this is a IntelliJ Platform problem.
