### ISSUE TITLE
Q: Any way to do this only for specific file type?

### ISSUE THREAD

**Issue by loeffel-io** [0verEngineer/InlineProblems#54]
example: 

.go: YES
.proto: NO

**Comment by 0verEngineer** [comment]
No, but this would be a very nice feature, i will check if this can be done 👍

**Comment by 0verEngineer** [comment]
@loeffel-io 
I have implemented this with a file extension blacklist in the settings, the beta should be available as soon as it is checked by JetBrains.
https://github.com/0verEngineer/InlineProblems/pull/56

**Comment by loeffel-io** [comment]
@0verEngineer 💯🙏
