### ISSUE TITLE
Tooltips or way for better readability?

### ISSUE THREAD

**Issue by Jarrodsz** [0verEngineer/InlineProblems#6]
<img width="771" alt="Screenshot 2023-01-10 at 02 51 31" src="https://user-images.githubusercontent.com/90145421/211443799-5bcc7262-c39f-4037-9614-9a8d3a3f3d19.png">

The errors are very hard to read, is there a config setting I could make in webstorm or Intellj to make them appear on the next line or as a popup modal?

**Comment by 0verEngineer** [comment]
@Jarrodsz 
There is an Option in the Settings "Force problems in the same line even if they are to long to fit" it is enabled by default for now until proper scrolling correction and multiline inlays are implemented.

If you turn this option off every problem that does not fit in the visible area is printed in the line above.

**Comment by heyuch** [comment]
> totally missed that, where would I find it? New to webstorm and did a search but it did not come up.

@Jarrodsz the plugin's setting path: Preferences | Appearance & Behavior | InlineProblems

or maybe you can try clicking here > [InlineProblems](jetbrains://idea/settings?name=Appearance+%26+Behavior--InlineProblems)

**Comment by 0verEngineer** [comment]
@Jarrodsz
I will add a setting to switch between problems above the line in question and below.

I will also check the idea about popups / tooltips as a setting, but i don't know if it will work performance wise.
